language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.1
    - hhvm

before_script:
    - travis_retry composer self-update

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 hello.c -o hello
  - ./hello
  - gcov hello.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
